#:kivy 1.0
#:import kivy kivy
#:import win kivy.core.window

#:kivy 1.7.1
#
# To load this file, Kivy looks if there is a Kv ﬁle with
# the same name as your App class in lowercase, minus
# "App" if it ends with "App". E.g: KivyAsteroid -> kivy.kv

<ControlClass, FloatLayout>:
    cols: 2
    row: 2
    canvas.before:
        Rectangle:
        # background image
        #source: '/home/atbe/dev/users/billclar/AsteroidCapturePkg-billclar1/src/AsteroidCapture/demos/gui_interaction/gui_images/asteroid-retrieval-1920.jpg'
           # source: 'background.jpg'
            pos: self.pos
            size: self.size
    # button to connect client to server
    Button:
        id: connect_client
        text: 'press to star simulation'
        # play with the size, or change this to a menu instead
        size_hint: 0.2, 0.1
        pos_hint: {'center_x':.1, 'center_y': .95}
        # root is the DisplayImage class
        on_press: root.schedule_client()  #bind button to function"
